LogConfig: true
Logger:
  AppName: opengate
  Build: dev
  Level: debug
AppNames:
- HTTP_SERVER
Server:
  Port: 8083
  GinMode: debug
  ReadTimeout: 30s
  WriteTimeout: 30s
  IdleTimeout: 120s
  MaxHeaderBytes: 1048576
  EnableCors: true
Repository:
  Name: OpenAuth
  Local: 
    RoutesFolderPath: ./resources/configs/routes/
  OpenAuth:
    Host: 192.168.1.100:8086
    Username: admin
    Password: admin123
    Timeout: 5s
    Tls: false
Service:
  ChangeDetector:
    RouteUpdateInterval: 10s
  Auth:
    Name: "OpenAuth"
    OpenAuth:
      Host: 192.168.1.100:8086
      Username: admin
      Password: admin123
      Tls: false
      Timeout: 30s
Cache:
  name: memory
Debug:
  Enabled: true
  EnablePprof: true