LogConfig: true
Logger:
  AppName: opengate
  Build: dev
  Level: debug
AppNames:
- HTTP_SERVER
- GATEWAY_SERVER
Server:
  GatewayPort: 8083
  AdminPort: 8080
  GinMode: release
  ReadTimeout: 30s
  WriteTimeout: 30s
  IdleTimeout: 120s
  MaxHeaderBytes: 1048576
  EnableCors: true
Repository:
  Name: PostgreSQL
  Local: 
    RoutesFolderPath: ./resources/configs/routes/
  OpenAuth:
    Host: 192.168.1.100:8086
    Username: admin
    Password: admin123
    Timeout: 5s
    Tls: false
  PostgreSQL:
    Name: Postgres
    Postgres:
      primary:
        Host: localhost
        Port: 5433
        Username: "admin"
        Password: OSwfiTlc1r5W7Z
        DBName: opengate
        SSLMode: disable
        MaxOpenConns: 10
        MaxIdleConns: 5
        ConnMaxLifetime: 5m
        ConnMaxIdleTime: 5m
      replica: []
Service:
  ChangeDetector:
    RouteUpdateInterval: 10s
  Auth:
    Name: "OpenAuth"
    OpenAuth:
      Host: 192.168.1.100:8086
      Username: admin
      Password: admin123
      Tls: false
      Timeout: 30s
  InitialRoutes:
    - Name: openauth
      PathPrefix: /openauth
      TargetURL: http://192.168.1.100:8085
      StripPrefix: false
      Authentication:
        Required: false
      Timeout: 30s
    - Name: opengate
      PathPrefix: /opengate
      TargetURL: http://localhost:8080
      StripPrefix: true
      Authentication:
        Required: false
    - Name: gateway 
      PathPrefix: /gateway
      TargetURL: http://localhost:8080
      StripPrefix: false
      Authentication:
        Required: false
Cache:
  name: memory
Debug:
  Enabled: true
  EnablePprof: true