// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               unknown
// source: proto/opengate/v1/opengate.proto

/* eslint-disable */
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";
import { PingRequest, PingResponse } from "../common/ping";
import {
  CreateConfigRequest,
  CreateConfigResponse,
  DeleteConfigRequest,
  DeleteConfigResponse,
  GetConfigRequest,
  GetConfigResponse,
  GetRoutesRequest,
  GetRoutesResponse,
  GetStatsRequest,
  GetStatsResponse,
  ListConfigsRequest,
  ListConfigsResponse,
  UpdateConfigRequest,
  UpdateConfigResponse,
} from "./config";

export const protobufPackage = "opengate.v1";

export type OpenGateServiceService = typeof OpenGateServiceService;
export const OpenGateServiceService = {
  /** Ping is a simple GET request that returns a Pong message. */
  ping: {
    path: "/opengate.v1.OpenGateService/Ping" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: PingRequest): Buffer => Buffer.from(PingRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): PingRequest => PingRequest.decode(value),
    responseSerialize: (value: PingResponse): Buffer => Buffer.from(PingResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): PingResponse => PingResponse.decode(value),
  },
  /** CreateConfig creates a new route configuration */
  createConfig: {
    path: "/opengate.v1.OpenGateService/CreateConfig" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: CreateConfigRequest): Buffer => Buffer.from(CreateConfigRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): CreateConfigRequest => CreateConfigRequest.decode(value),
    responseSerialize: (value: CreateConfigResponse): Buffer =>
      Buffer.from(CreateConfigResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): CreateConfigResponse => CreateConfigResponse.decode(value),
  },
  /** GetConfig retrieves a config by ID */
  getConfig: {
    path: "/opengate.v1.OpenGateService/GetConfig" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: GetConfigRequest): Buffer => Buffer.from(GetConfigRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetConfigRequest => GetConfigRequest.decode(value),
    responseSerialize: (value: GetConfigResponse): Buffer => Buffer.from(GetConfigResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): GetConfigResponse => GetConfigResponse.decode(value),
  },
  /** ListConfigs lists configs with pagination */
  listConfigs: {
    path: "/opengate.v1.OpenGateService/ListConfigs" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: ListConfigsRequest): Buffer => Buffer.from(ListConfigsRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): ListConfigsRequest => ListConfigsRequest.decode(value),
    responseSerialize: (value: ListConfigsResponse): Buffer => Buffer.from(ListConfigsResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): ListConfigsResponse => ListConfigsResponse.decode(value),
  },
  /** UpdateConfig updates an existing config */
  updateConfig: {
    path: "/opengate.v1.OpenGateService/UpdateConfig" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: UpdateConfigRequest): Buffer => Buffer.from(UpdateConfigRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): UpdateConfigRequest => UpdateConfigRequest.decode(value),
    responseSerialize: (value: UpdateConfigResponse): Buffer =>
      Buffer.from(UpdateConfigResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): UpdateConfigResponse => UpdateConfigResponse.decode(value),
  },
  /** DeleteConfig deletes a config by ID */
  deleteConfig: {
    path: "/opengate.v1.OpenGateService/DeleteConfig" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: DeleteConfigRequest): Buffer => Buffer.from(DeleteConfigRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): DeleteConfigRequest => DeleteConfigRequest.decode(value),
    responseSerialize: (value: DeleteConfigResponse): Buffer =>
      Buffer.from(DeleteConfigResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): DeleteConfigResponse => DeleteConfigResponse.decode(value),
  },
  /** GetRoutes retrieves all routes for routing purposes */
  getRoutes: {
    path: "/opengate.v1.OpenGateService/GetRoutes" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: GetRoutesRequest): Buffer => Buffer.from(GetRoutesRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetRoutesRequest => GetRoutesRequest.decode(value),
    responseSerialize: (value: GetRoutesResponse): Buffer => Buffer.from(GetRoutesResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): GetRoutesResponse => GetRoutesResponse.decode(value),
  },
  /** GetStats retrieves dashboard statistics */
  getStats: {
    path: "/opengate.v1.OpenGateService/GetStats" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: GetStatsRequest): Buffer => Buffer.from(GetStatsRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetStatsRequest => GetStatsRequest.decode(value),
    responseSerialize: (value: GetStatsResponse): Buffer => Buffer.from(GetStatsResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): GetStatsResponse => GetStatsResponse.decode(value),
  },
} as const;

export interface OpenGateServiceServer extends UntypedServiceImplementation {
  /** Ping is a simple GET request that returns a Pong message. */
  ping: handleUnaryCall<PingRequest, PingResponse>;
  /** CreateConfig creates a new route configuration */
  createConfig: handleUnaryCall<CreateConfigRequest, CreateConfigResponse>;
  /** GetConfig retrieves a config by ID */
  getConfig: handleUnaryCall<GetConfigRequest, GetConfigResponse>;
  /** ListConfigs lists configs with pagination */
  listConfigs: handleUnaryCall<ListConfigsRequest, ListConfigsResponse>;
  /** UpdateConfig updates an existing config */
  updateConfig: handleUnaryCall<UpdateConfigRequest, UpdateConfigResponse>;
  /** DeleteConfig deletes a config by ID */
  deleteConfig: handleUnaryCall<DeleteConfigRequest, DeleteConfigResponse>;
  /** GetRoutes retrieves all routes for routing purposes */
  getRoutes: handleUnaryCall<GetRoutesRequest, GetRoutesResponse>;
  /** GetStats retrieves dashboard statistics */
  getStats: handleUnaryCall<GetStatsRequest, GetStatsResponse>;
}

export interface OpenGateServiceClient extends Client {
  /** Ping is a simple GET request that returns a Pong message. */
  ping(request: PingRequest, callback: (error: ServiceError | null, response: PingResponse) => void): ClientUnaryCall;
  ping(
    request: PingRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: PingResponse) => void,
  ): ClientUnaryCall;
  ping(
    request: PingRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: PingResponse) => void,
  ): ClientUnaryCall;
  /** CreateConfig creates a new route configuration */
  createConfig(
    request: CreateConfigRequest,
    callback: (error: ServiceError | null, response: CreateConfigResponse) => void,
  ): ClientUnaryCall;
  createConfig(
    request: CreateConfigRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: CreateConfigResponse) => void,
  ): ClientUnaryCall;
  createConfig(
    request: CreateConfigRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: CreateConfigResponse) => void,
  ): ClientUnaryCall;
  /** GetConfig retrieves a config by ID */
  getConfig(
    request: GetConfigRequest,
    callback: (error: ServiceError | null, response: GetConfigResponse) => void,
  ): ClientUnaryCall;
  getConfig(
    request: GetConfigRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: GetConfigResponse) => void,
  ): ClientUnaryCall;
  getConfig(
    request: GetConfigRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: GetConfigResponse) => void,
  ): ClientUnaryCall;
  /** ListConfigs lists configs with pagination */
  listConfigs(
    request: ListConfigsRequest,
    callback: (error: ServiceError | null, response: ListConfigsResponse) => void,
  ): ClientUnaryCall;
  listConfigs(
    request: ListConfigsRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: ListConfigsResponse) => void,
  ): ClientUnaryCall;
  listConfigs(
    request: ListConfigsRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: ListConfigsResponse) => void,
  ): ClientUnaryCall;
  /** UpdateConfig updates an existing config */
  updateConfig(
    request: UpdateConfigRequest,
    callback: (error: ServiceError | null, response: UpdateConfigResponse) => void,
  ): ClientUnaryCall;
  updateConfig(
    request: UpdateConfigRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: UpdateConfigResponse) => void,
  ): ClientUnaryCall;
  updateConfig(
    request: UpdateConfigRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: UpdateConfigResponse) => void,
  ): ClientUnaryCall;
  /** DeleteConfig deletes a config by ID */
  deleteConfig(
    request: DeleteConfigRequest,
    callback: (error: ServiceError | null, response: DeleteConfigResponse) => void,
  ): ClientUnaryCall;
  deleteConfig(
    request: DeleteConfigRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: DeleteConfigResponse) => void,
  ): ClientUnaryCall;
  deleteConfig(
    request: DeleteConfigRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: DeleteConfigResponse) => void,
  ): ClientUnaryCall;
  /** GetRoutes retrieves all routes for routing purposes */
  getRoutes(
    request: GetRoutesRequest,
    callback: (error: ServiceError | null, response: GetRoutesResponse) => void,
  ): ClientUnaryCall;
  getRoutes(
    request: GetRoutesRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: GetRoutesResponse) => void,
  ): ClientUnaryCall;
  getRoutes(
    request: GetRoutesRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: GetRoutesResponse) => void,
  ): ClientUnaryCall;
  /** GetStats retrieves dashboard statistics */
  getStats(
    request: GetStatsRequest,
    callback: (error: ServiceError | null, response: GetStatsResponse) => void,
  ): ClientUnaryCall;
  getStats(
    request: GetStatsRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: GetStatsResponse) => void,
  ): ClientUnaryCall;
  getStats(
    request: GetStatsRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: GetStatsResponse) => void,
  ): ClientUnaryCall;
}

export const OpenGateServiceClient = makeGenericClientConstructor(
  OpenGateServiceService,
  "opengate.v1.OpenGateService",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): OpenGateServiceClient;
  service: typeof OpenGateServiceService;
  serviceName: string;
};
