// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               unknown
// source: proto/opengate/v1/config.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "opengate.v1";

/** AuthenticationException defines paths/methods excepted from authentication rules */
export interface AuthenticationException {
  path: string;
  methods: string[];
}

/** Authentication defines authentication settings for a route */
export interface Authentication {
  required: boolean;
  /**
   * if required is true, excepted paths/methods do not require authentication
   * if required is false, excepted paths/methods require authentication
   */
  except: AuthenticationException[];
}

/** Config represents a service route configuration */
export interface Config {
  id: string;
  name: string;
  pathPrefix: string;
  targetUrl: string;
  stripPrefix: boolean;
  authentication: Authentication | undefined;
  middleware: string[];
  /** Timeout in nanoseconds */
  timeout: string;
  /** Unix timestamp */
  createdAt: string;
  /** Unix timestamp */
  updatedAt: string;
}

/** CreateConfigRequest is the request to create a new config */
export interface CreateConfigRequest {
  name: string;
  pathPrefix: string;
  targetUrl: string;
  stripPrefix: boolean;
  authentication: Authentication | undefined;
  middleware: string[];
  /** Timeout in nanoseconds, default 30s if not provided */
  timeout: string;
}

/** CreateConfigResponse is the response after creating a config */
export interface CreateConfigResponse {
  config: Config | undefined;
  message: string;
}

/** GetConfigRequest is the request to get a config by ID */
export interface GetConfigRequest {
  id: string;
}

/** GetConfigResponse is the response containing the requested config */
export interface GetConfigResponse {
  config: Config | undefined;
  message: string;
}

/** ListConfigsRequest is the request to list configs with pagination */
export interface ListConfigsRequest {
  limit: number;
  offset: number;
  /** Optional search term for name */
  search: string;
}

/** ListConfigsResponse is the response containing a list of configs */
export interface ListConfigsResponse {
  configs: Config[];
  /** Total count for pagination */
  total: number;
  message: string;
}

/** GetRoutesRequest is the request to get all routes for routing purposes */
export interface GetRoutesRequest {
}

/** Route represents a simplified route for the routing manager */
export interface Route {
  name: string;
  pathPrefix: string;
  targetUrl: string;
  stripPrefix: boolean;
  authentication: Authentication | undefined;
  middleware: string[];
  timeout: string;
  updatedAt: string;
}

/** GetRoutesResponse contains all routes for the routing manager */
export interface GetRoutesResponse {
  routes: Route[];
  message: string;
}

/** UpdateConfigRequest is the request to update an existing config */
export interface UpdateConfigRequest {
  id: string;
  name: string;
  pathPrefix: string;
  targetUrl: string;
  stripPrefix: boolean;
  authentication: Authentication | undefined;
  middleware: string[];
  timeout: string;
}

/** UpdateConfigResponse is the response after updating a config */
export interface UpdateConfigResponse {
  config: Config | undefined;
  message: string;
}

/** DeleteConfigRequest is the request to delete a config */
export interface DeleteConfigRequest {
  id: string;
}

/** DeleteConfigResponse is the response after deleting a config */
export interface DeleteConfigResponse {
  message: string;
}

function createBaseAuthenticationException(): AuthenticationException {
  return { path: "", methods: [] };
}

export const AuthenticationException: MessageFns<AuthenticationException> = {
  encode(message: AuthenticationException, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.path !== "") {
      writer.uint32(10).string(message.path);
    }
    for (const v of message.methods) {
      writer.uint32(18).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AuthenticationException {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAuthenticationException();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.path = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.methods.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AuthenticationException {
    return {
      path: isSet(object.path) ? globalThis.String(object.path) : "",
      methods: globalThis.Array.isArray(object?.methods) ? object.methods.map((e: any) => globalThis.String(e)) : [],
    };
  },

  toJSON(message: AuthenticationException): unknown {
    const obj: any = {};
    if (message.path !== "") {
      obj.path = message.path;
    }
    if (message.methods?.length) {
      obj.methods = message.methods;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AuthenticationException>, I>>(base?: I): AuthenticationException {
    return AuthenticationException.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AuthenticationException>, I>>(object: I): AuthenticationException {
    const message = createBaseAuthenticationException();
    message.path = object.path ?? "";
    message.methods = object.methods?.map((e) => e) || [];
    return message;
  },
};

function createBaseAuthentication(): Authentication {
  return { required: false, except: [] };
}

export const Authentication: MessageFns<Authentication> = {
  encode(message: Authentication, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.required !== false) {
      writer.uint32(8).bool(message.required);
    }
    for (const v of message.except) {
      AuthenticationException.encode(v!, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Authentication {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAuthentication();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.required = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.except.push(AuthenticationException.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Authentication {
    return {
      required: isSet(object.required) ? globalThis.Boolean(object.required) : false,
      except: globalThis.Array.isArray(object?.except)
        ? object.except.map((e: any) => AuthenticationException.fromJSON(e))
        : [],
    };
  },

  toJSON(message: Authentication): unknown {
    const obj: any = {};
    if (message.required !== false) {
      obj.required = message.required;
    }
    if (message.except?.length) {
      obj.except = message.except.map((e) => AuthenticationException.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Authentication>, I>>(base?: I): Authentication {
    return Authentication.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Authentication>, I>>(object: I): Authentication {
    const message = createBaseAuthentication();
    message.required = object.required ?? false;
    message.except = object.except?.map((e) => AuthenticationException.fromPartial(e)) || [];
    return message;
  },
};

function createBaseConfig(): Config {
  return {
    id: "0",
    name: "",
    pathPrefix: "",
    targetUrl: "",
    stripPrefix: false,
    authentication: undefined,
    middleware: [],
    timeout: "0",
    createdAt: "0",
    updatedAt: "0",
  };
}

export const Config: MessageFns<Config> = {
  encode(message: Config, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "0") {
      writer.uint32(8).int64(message.id);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.pathPrefix !== "") {
      writer.uint32(26).string(message.pathPrefix);
    }
    if (message.targetUrl !== "") {
      writer.uint32(34).string(message.targetUrl);
    }
    if (message.stripPrefix !== false) {
      writer.uint32(40).bool(message.stripPrefix);
    }
    if (message.authentication !== undefined) {
      Authentication.encode(message.authentication, writer.uint32(50).fork()).join();
    }
    for (const v of message.middleware) {
      writer.uint32(58).string(v!);
    }
    if (message.timeout !== "0") {
      writer.uint32(64).int64(message.timeout);
    }
    if (message.createdAt !== "0") {
      writer.uint32(72).int64(message.createdAt);
    }
    if (message.updatedAt !== "0") {
      writer.uint32(80).int64(message.updatedAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Config {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.int64().toString();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.pathPrefix = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.targetUrl = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.stripPrefix = reader.bool();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.authentication = Authentication.decode(reader, reader.uint32());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.middleware.push(reader.string());
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.timeout = reader.int64().toString();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.createdAt = reader.int64().toString();
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.updatedAt = reader.int64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Config {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "0",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      pathPrefix: isSet(object.pathPrefix)
        ? globalThis.String(object.pathPrefix)
        : isSet(object.path_prefix)
        ? globalThis.String(object.path_prefix)
        : "",
      targetUrl: isSet(object.targetUrl)
        ? globalThis.String(object.targetUrl)
        : isSet(object.target_url)
        ? globalThis.String(object.target_url)
        : "",
      stripPrefix: isSet(object.stripPrefix)
        ? globalThis.Boolean(object.stripPrefix)
        : isSet(object.strip_prefix)
        ? globalThis.Boolean(object.strip_prefix)
        : false,
      authentication: isSet(object.authentication) ? Authentication.fromJSON(object.authentication) : undefined,
      middleware: globalThis.Array.isArray(object?.middleware)
        ? object.middleware.map((e: any) => globalThis.String(e))
        : [],
      timeout: isSet(object.timeout) ? globalThis.String(object.timeout) : "0",
      createdAt: isSet(object.createdAt)
        ? globalThis.String(object.createdAt)
        : isSet(object.created_at)
        ? globalThis.String(object.created_at)
        : "0",
      updatedAt: isSet(object.updatedAt)
        ? globalThis.String(object.updatedAt)
        : isSet(object.updated_at)
        ? globalThis.String(object.updated_at)
        : "0",
    };
  },

  toJSON(message: Config): unknown {
    const obj: any = {};
    if (message.id !== "0") {
      obj.id = message.id;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.pathPrefix !== "") {
      obj.pathPrefix = message.pathPrefix;
    }
    if (message.targetUrl !== "") {
      obj.targetUrl = message.targetUrl;
    }
    if (message.stripPrefix !== false) {
      obj.stripPrefix = message.stripPrefix;
    }
    if (message.authentication !== undefined) {
      obj.authentication = Authentication.toJSON(message.authentication);
    }
    if (message.middleware?.length) {
      obj.middleware = message.middleware;
    }
    if (message.timeout !== "0") {
      obj.timeout = message.timeout;
    }
    if (message.createdAt !== "0") {
      obj.createdAt = message.createdAt;
    }
    if (message.updatedAt !== "0") {
      obj.updatedAt = message.updatedAt;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Config>, I>>(base?: I): Config {
    return Config.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Config>, I>>(object: I): Config {
    const message = createBaseConfig();
    message.id = object.id ?? "0";
    message.name = object.name ?? "";
    message.pathPrefix = object.pathPrefix ?? "";
    message.targetUrl = object.targetUrl ?? "";
    message.stripPrefix = object.stripPrefix ?? false;
    message.authentication = (object.authentication !== undefined && object.authentication !== null)
      ? Authentication.fromPartial(object.authentication)
      : undefined;
    message.middleware = object.middleware?.map((e) => e) || [];
    message.timeout = object.timeout ?? "0";
    message.createdAt = object.createdAt ?? "0";
    message.updatedAt = object.updatedAt ?? "0";
    return message;
  },
};

function createBaseCreateConfigRequest(): CreateConfigRequest {
  return {
    name: "",
    pathPrefix: "",
    targetUrl: "",
    stripPrefix: false,
    authentication: undefined,
    middleware: [],
    timeout: "0",
  };
}

export const CreateConfigRequest: MessageFns<CreateConfigRequest> = {
  encode(message: CreateConfigRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.pathPrefix !== "") {
      writer.uint32(18).string(message.pathPrefix);
    }
    if (message.targetUrl !== "") {
      writer.uint32(26).string(message.targetUrl);
    }
    if (message.stripPrefix !== false) {
      writer.uint32(32).bool(message.stripPrefix);
    }
    if (message.authentication !== undefined) {
      Authentication.encode(message.authentication, writer.uint32(42).fork()).join();
    }
    for (const v of message.middleware) {
      writer.uint32(50).string(v!);
    }
    if (message.timeout !== "0") {
      writer.uint32(56).int64(message.timeout);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateConfigRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateConfigRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.pathPrefix = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.targetUrl = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.stripPrefix = reader.bool();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.authentication = Authentication.decode(reader, reader.uint32());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.middleware.push(reader.string());
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.timeout = reader.int64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateConfigRequest {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      pathPrefix: isSet(object.pathPrefix)
        ? globalThis.String(object.pathPrefix)
        : isSet(object.path_prefix)
        ? globalThis.String(object.path_prefix)
        : "",
      targetUrl: isSet(object.targetUrl)
        ? globalThis.String(object.targetUrl)
        : isSet(object.target_url)
        ? globalThis.String(object.target_url)
        : "",
      stripPrefix: isSet(object.stripPrefix)
        ? globalThis.Boolean(object.stripPrefix)
        : isSet(object.strip_prefix)
        ? globalThis.Boolean(object.strip_prefix)
        : false,
      authentication: isSet(object.authentication) ? Authentication.fromJSON(object.authentication) : undefined,
      middleware: globalThis.Array.isArray(object?.middleware)
        ? object.middleware.map((e: any) => globalThis.String(e))
        : [],
      timeout: isSet(object.timeout) ? globalThis.String(object.timeout) : "0",
    };
  },

  toJSON(message: CreateConfigRequest): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.pathPrefix !== "") {
      obj.pathPrefix = message.pathPrefix;
    }
    if (message.targetUrl !== "") {
      obj.targetUrl = message.targetUrl;
    }
    if (message.stripPrefix !== false) {
      obj.stripPrefix = message.stripPrefix;
    }
    if (message.authentication !== undefined) {
      obj.authentication = Authentication.toJSON(message.authentication);
    }
    if (message.middleware?.length) {
      obj.middleware = message.middleware;
    }
    if (message.timeout !== "0") {
      obj.timeout = message.timeout;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateConfigRequest>, I>>(base?: I): CreateConfigRequest {
    return CreateConfigRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateConfigRequest>, I>>(object: I): CreateConfigRequest {
    const message = createBaseCreateConfigRequest();
    message.name = object.name ?? "";
    message.pathPrefix = object.pathPrefix ?? "";
    message.targetUrl = object.targetUrl ?? "";
    message.stripPrefix = object.stripPrefix ?? false;
    message.authentication = (object.authentication !== undefined && object.authentication !== null)
      ? Authentication.fromPartial(object.authentication)
      : undefined;
    message.middleware = object.middleware?.map((e) => e) || [];
    message.timeout = object.timeout ?? "0";
    return message;
  },
};

function createBaseCreateConfigResponse(): CreateConfigResponse {
  return { config: undefined, message: "" };
}

export const CreateConfigResponse: MessageFns<CreateConfigResponse> = {
  encode(message: CreateConfigResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.config !== undefined) {
      Config.encode(message.config, writer.uint32(10).fork()).join();
    }
    if (message.message !== "") {
      writer.uint32(18).string(message.message);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateConfigResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateConfigResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.config = Config.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.message = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateConfigResponse {
    return {
      config: isSet(object.config) ? Config.fromJSON(object.config) : undefined,
      message: isSet(object.message) ? globalThis.String(object.message) : "",
    };
  },

  toJSON(message: CreateConfigResponse): unknown {
    const obj: any = {};
    if (message.config !== undefined) {
      obj.config = Config.toJSON(message.config);
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateConfigResponse>, I>>(base?: I): CreateConfigResponse {
    return CreateConfigResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateConfigResponse>, I>>(object: I): CreateConfigResponse {
    const message = createBaseCreateConfigResponse();
    message.config = (object.config !== undefined && object.config !== null)
      ? Config.fromPartial(object.config)
      : undefined;
    message.message = object.message ?? "";
    return message;
  },
};

function createBaseGetConfigRequest(): GetConfigRequest {
  return { id: "0" };
}

export const GetConfigRequest: MessageFns<GetConfigRequest> = {
  encode(message: GetConfigRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "0") {
      writer.uint32(8).int64(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetConfigRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetConfigRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.int64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetConfigRequest {
    return { id: isSet(object.id) ? globalThis.String(object.id) : "0" };
  },

  toJSON(message: GetConfigRequest): unknown {
    const obj: any = {};
    if (message.id !== "0") {
      obj.id = message.id;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetConfigRequest>, I>>(base?: I): GetConfigRequest {
    return GetConfigRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetConfigRequest>, I>>(object: I): GetConfigRequest {
    const message = createBaseGetConfigRequest();
    message.id = object.id ?? "0";
    return message;
  },
};

function createBaseGetConfigResponse(): GetConfigResponse {
  return { config: undefined, message: "" };
}

export const GetConfigResponse: MessageFns<GetConfigResponse> = {
  encode(message: GetConfigResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.config !== undefined) {
      Config.encode(message.config, writer.uint32(10).fork()).join();
    }
    if (message.message !== "") {
      writer.uint32(18).string(message.message);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetConfigResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetConfigResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.config = Config.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.message = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetConfigResponse {
    return {
      config: isSet(object.config) ? Config.fromJSON(object.config) : undefined,
      message: isSet(object.message) ? globalThis.String(object.message) : "",
    };
  },

  toJSON(message: GetConfigResponse): unknown {
    const obj: any = {};
    if (message.config !== undefined) {
      obj.config = Config.toJSON(message.config);
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetConfigResponse>, I>>(base?: I): GetConfigResponse {
    return GetConfigResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetConfigResponse>, I>>(object: I): GetConfigResponse {
    const message = createBaseGetConfigResponse();
    message.config = (object.config !== undefined && object.config !== null)
      ? Config.fromPartial(object.config)
      : undefined;
    message.message = object.message ?? "";
    return message;
  },
};

function createBaseListConfigsRequest(): ListConfigsRequest {
  return { limit: 0, offset: 0, search: "" };
}

export const ListConfigsRequest: MessageFns<ListConfigsRequest> = {
  encode(message: ListConfigsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.limit !== 0) {
      writer.uint32(8).int32(message.limit);
    }
    if (message.offset !== 0) {
      writer.uint32(16).int32(message.offset);
    }
    if (message.search !== "") {
      writer.uint32(26).string(message.search);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListConfigsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListConfigsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.limit = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.offset = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.search = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListConfigsRequest {
    return {
      limit: isSet(object.limit) ? globalThis.Number(object.limit) : 0,
      offset: isSet(object.offset) ? globalThis.Number(object.offset) : 0,
      search: isSet(object.search) ? globalThis.String(object.search) : "",
    };
  },

  toJSON(message: ListConfigsRequest): unknown {
    const obj: any = {};
    if (message.limit !== 0) {
      obj.limit = Math.round(message.limit);
    }
    if (message.offset !== 0) {
      obj.offset = Math.round(message.offset);
    }
    if (message.search !== "") {
      obj.search = message.search;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListConfigsRequest>, I>>(base?: I): ListConfigsRequest {
    return ListConfigsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListConfigsRequest>, I>>(object: I): ListConfigsRequest {
    const message = createBaseListConfigsRequest();
    message.limit = object.limit ?? 0;
    message.offset = object.offset ?? 0;
    message.search = object.search ?? "";
    return message;
  },
};

function createBaseListConfigsResponse(): ListConfigsResponse {
  return { configs: [], total: 0, message: "" };
}

export const ListConfigsResponse: MessageFns<ListConfigsResponse> = {
  encode(message: ListConfigsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.configs) {
      Config.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.total !== 0) {
      writer.uint32(16).int32(message.total);
    }
    if (message.message !== "") {
      writer.uint32(26).string(message.message);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListConfigsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListConfigsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.configs.push(Config.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.total = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.message = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListConfigsResponse {
    return {
      configs: globalThis.Array.isArray(object?.configs) ? object.configs.map((e: any) => Config.fromJSON(e)) : [],
      total: isSet(object.total) ? globalThis.Number(object.total) : 0,
      message: isSet(object.message) ? globalThis.String(object.message) : "",
    };
  },

  toJSON(message: ListConfigsResponse): unknown {
    const obj: any = {};
    if (message.configs?.length) {
      obj.configs = message.configs.map((e) => Config.toJSON(e));
    }
    if (message.total !== 0) {
      obj.total = Math.round(message.total);
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListConfigsResponse>, I>>(base?: I): ListConfigsResponse {
    return ListConfigsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListConfigsResponse>, I>>(object: I): ListConfigsResponse {
    const message = createBaseListConfigsResponse();
    message.configs = object.configs?.map((e) => Config.fromPartial(e)) || [];
    message.total = object.total ?? 0;
    message.message = object.message ?? "";
    return message;
  },
};

function createBaseGetRoutesRequest(): GetRoutesRequest {
  return {};
}

export const GetRoutesRequest: MessageFns<GetRoutesRequest> = {
  encode(_: GetRoutesRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetRoutesRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetRoutesRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): GetRoutesRequest {
    return {};
  },

  toJSON(_: GetRoutesRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<GetRoutesRequest>, I>>(base?: I): GetRoutesRequest {
    return GetRoutesRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetRoutesRequest>, I>>(_: I): GetRoutesRequest {
    const message = createBaseGetRoutesRequest();
    return message;
  },
};

function createBaseRoute(): Route {
  return {
    name: "",
    pathPrefix: "",
    targetUrl: "",
    stripPrefix: false,
    authentication: undefined,
    middleware: [],
    timeout: "0",
    updatedAt: "0",
  };
}

export const Route: MessageFns<Route> = {
  encode(message: Route, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.pathPrefix !== "") {
      writer.uint32(18).string(message.pathPrefix);
    }
    if (message.targetUrl !== "") {
      writer.uint32(26).string(message.targetUrl);
    }
    if (message.stripPrefix !== false) {
      writer.uint32(32).bool(message.stripPrefix);
    }
    if (message.authentication !== undefined) {
      Authentication.encode(message.authentication, writer.uint32(42).fork()).join();
    }
    for (const v of message.middleware) {
      writer.uint32(50).string(v!);
    }
    if (message.timeout !== "0") {
      writer.uint32(56).int64(message.timeout);
    }
    if (message.updatedAt !== "0") {
      writer.uint32(64).int64(message.updatedAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Route {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRoute();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.pathPrefix = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.targetUrl = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.stripPrefix = reader.bool();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.authentication = Authentication.decode(reader, reader.uint32());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.middleware.push(reader.string());
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.timeout = reader.int64().toString();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.updatedAt = reader.int64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Route {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      pathPrefix: isSet(object.pathPrefix)
        ? globalThis.String(object.pathPrefix)
        : isSet(object.path_prefix)
        ? globalThis.String(object.path_prefix)
        : "",
      targetUrl: isSet(object.targetUrl)
        ? globalThis.String(object.targetUrl)
        : isSet(object.target_url)
        ? globalThis.String(object.target_url)
        : "",
      stripPrefix: isSet(object.stripPrefix)
        ? globalThis.Boolean(object.stripPrefix)
        : isSet(object.strip_prefix)
        ? globalThis.Boolean(object.strip_prefix)
        : false,
      authentication: isSet(object.authentication) ? Authentication.fromJSON(object.authentication) : undefined,
      middleware: globalThis.Array.isArray(object?.middleware)
        ? object.middleware.map((e: any) => globalThis.String(e))
        : [],
      timeout: isSet(object.timeout) ? globalThis.String(object.timeout) : "0",
      updatedAt: isSet(object.updatedAt)
        ? globalThis.String(object.updatedAt)
        : isSet(object.updated_at)
        ? globalThis.String(object.updated_at)
        : "0",
    };
  },

  toJSON(message: Route): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.pathPrefix !== "") {
      obj.pathPrefix = message.pathPrefix;
    }
    if (message.targetUrl !== "") {
      obj.targetUrl = message.targetUrl;
    }
    if (message.stripPrefix !== false) {
      obj.stripPrefix = message.stripPrefix;
    }
    if (message.authentication !== undefined) {
      obj.authentication = Authentication.toJSON(message.authentication);
    }
    if (message.middleware?.length) {
      obj.middleware = message.middleware;
    }
    if (message.timeout !== "0") {
      obj.timeout = message.timeout;
    }
    if (message.updatedAt !== "0") {
      obj.updatedAt = message.updatedAt;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Route>, I>>(base?: I): Route {
    return Route.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Route>, I>>(object: I): Route {
    const message = createBaseRoute();
    message.name = object.name ?? "";
    message.pathPrefix = object.pathPrefix ?? "";
    message.targetUrl = object.targetUrl ?? "";
    message.stripPrefix = object.stripPrefix ?? false;
    message.authentication = (object.authentication !== undefined && object.authentication !== null)
      ? Authentication.fromPartial(object.authentication)
      : undefined;
    message.middleware = object.middleware?.map((e) => e) || [];
    message.timeout = object.timeout ?? "0";
    message.updatedAt = object.updatedAt ?? "0";
    return message;
  },
};

function createBaseGetRoutesResponse(): GetRoutesResponse {
  return { routes: [], message: "" };
}

export const GetRoutesResponse: MessageFns<GetRoutesResponse> = {
  encode(message: GetRoutesResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.routes) {
      Route.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.message !== "") {
      writer.uint32(18).string(message.message);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetRoutesResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetRoutesResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.routes.push(Route.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.message = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetRoutesResponse {
    return {
      routes: globalThis.Array.isArray(object?.routes) ? object.routes.map((e: any) => Route.fromJSON(e)) : [],
      message: isSet(object.message) ? globalThis.String(object.message) : "",
    };
  },

  toJSON(message: GetRoutesResponse): unknown {
    const obj: any = {};
    if (message.routes?.length) {
      obj.routes = message.routes.map((e) => Route.toJSON(e));
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetRoutesResponse>, I>>(base?: I): GetRoutesResponse {
    return GetRoutesResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetRoutesResponse>, I>>(object: I): GetRoutesResponse {
    const message = createBaseGetRoutesResponse();
    message.routes = object.routes?.map((e) => Route.fromPartial(e)) || [];
    message.message = object.message ?? "";
    return message;
  },
};

function createBaseUpdateConfigRequest(): UpdateConfigRequest {
  return {
    id: "0",
    name: "",
    pathPrefix: "",
    targetUrl: "",
    stripPrefix: false,
    authentication: undefined,
    middleware: [],
    timeout: "0",
  };
}

export const UpdateConfigRequest: MessageFns<UpdateConfigRequest> = {
  encode(message: UpdateConfigRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "0") {
      writer.uint32(8).int64(message.id);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.pathPrefix !== "") {
      writer.uint32(26).string(message.pathPrefix);
    }
    if (message.targetUrl !== "") {
      writer.uint32(34).string(message.targetUrl);
    }
    if (message.stripPrefix !== false) {
      writer.uint32(40).bool(message.stripPrefix);
    }
    if (message.authentication !== undefined) {
      Authentication.encode(message.authentication, writer.uint32(50).fork()).join();
    }
    for (const v of message.middleware) {
      writer.uint32(58).string(v!);
    }
    if (message.timeout !== "0") {
      writer.uint32(64).int64(message.timeout);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateConfigRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateConfigRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.int64().toString();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.pathPrefix = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.targetUrl = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.stripPrefix = reader.bool();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.authentication = Authentication.decode(reader, reader.uint32());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.middleware.push(reader.string());
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.timeout = reader.int64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateConfigRequest {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "0",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      pathPrefix: isSet(object.pathPrefix)
        ? globalThis.String(object.pathPrefix)
        : isSet(object.path_prefix)
        ? globalThis.String(object.path_prefix)
        : "",
      targetUrl: isSet(object.targetUrl)
        ? globalThis.String(object.targetUrl)
        : isSet(object.target_url)
        ? globalThis.String(object.target_url)
        : "",
      stripPrefix: isSet(object.stripPrefix)
        ? globalThis.Boolean(object.stripPrefix)
        : isSet(object.strip_prefix)
        ? globalThis.Boolean(object.strip_prefix)
        : false,
      authentication: isSet(object.authentication) ? Authentication.fromJSON(object.authentication) : undefined,
      middleware: globalThis.Array.isArray(object?.middleware)
        ? object.middleware.map((e: any) => globalThis.String(e))
        : [],
      timeout: isSet(object.timeout) ? globalThis.String(object.timeout) : "0",
    };
  },

  toJSON(message: UpdateConfigRequest): unknown {
    const obj: any = {};
    if (message.id !== "0") {
      obj.id = message.id;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.pathPrefix !== "") {
      obj.pathPrefix = message.pathPrefix;
    }
    if (message.targetUrl !== "") {
      obj.targetUrl = message.targetUrl;
    }
    if (message.stripPrefix !== false) {
      obj.stripPrefix = message.stripPrefix;
    }
    if (message.authentication !== undefined) {
      obj.authentication = Authentication.toJSON(message.authentication);
    }
    if (message.middleware?.length) {
      obj.middleware = message.middleware;
    }
    if (message.timeout !== "0") {
      obj.timeout = message.timeout;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UpdateConfigRequest>, I>>(base?: I): UpdateConfigRequest {
    return UpdateConfigRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpdateConfigRequest>, I>>(object: I): UpdateConfigRequest {
    const message = createBaseUpdateConfigRequest();
    message.id = object.id ?? "0";
    message.name = object.name ?? "";
    message.pathPrefix = object.pathPrefix ?? "";
    message.targetUrl = object.targetUrl ?? "";
    message.stripPrefix = object.stripPrefix ?? false;
    message.authentication = (object.authentication !== undefined && object.authentication !== null)
      ? Authentication.fromPartial(object.authentication)
      : undefined;
    message.middleware = object.middleware?.map((e) => e) || [];
    message.timeout = object.timeout ?? "0";
    return message;
  },
};

function createBaseUpdateConfigResponse(): UpdateConfigResponse {
  return { config: undefined, message: "" };
}

export const UpdateConfigResponse: MessageFns<UpdateConfigResponse> = {
  encode(message: UpdateConfigResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.config !== undefined) {
      Config.encode(message.config, writer.uint32(10).fork()).join();
    }
    if (message.message !== "") {
      writer.uint32(18).string(message.message);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateConfigResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateConfigResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.config = Config.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.message = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateConfigResponse {
    return {
      config: isSet(object.config) ? Config.fromJSON(object.config) : undefined,
      message: isSet(object.message) ? globalThis.String(object.message) : "",
    };
  },

  toJSON(message: UpdateConfigResponse): unknown {
    const obj: any = {};
    if (message.config !== undefined) {
      obj.config = Config.toJSON(message.config);
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UpdateConfigResponse>, I>>(base?: I): UpdateConfigResponse {
    return UpdateConfigResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpdateConfigResponse>, I>>(object: I): UpdateConfigResponse {
    const message = createBaseUpdateConfigResponse();
    message.config = (object.config !== undefined && object.config !== null)
      ? Config.fromPartial(object.config)
      : undefined;
    message.message = object.message ?? "";
    return message;
  },
};

function createBaseDeleteConfigRequest(): DeleteConfigRequest {
  return { id: "0" };
}

export const DeleteConfigRequest: MessageFns<DeleteConfigRequest> = {
  encode(message: DeleteConfigRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "0") {
      writer.uint32(8).int64(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeleteConfigRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeleteConfigRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.int64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DeleteConfigRequest {
    return { id: isSet(object.id) ? globalThis.String(object.id) : "0" };
  },

  toJSON(message: DeleteConfigRequest): unknown {
    const obj: any = {};
    if (message.id !== "0") {
      obj.id = message.id;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DeleteConfigRequest>, I>>(base?: I): DeleteConfigRequest {
    return DeleteConfigRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DeleteConfigRequest>, I>>(object: I): DeleteConfigRequest {
    const message = createBaseDeleteConfigRequest();
    message.id = object.id ?? "0";
    return message;
  },
};

function createBaseDeleteConfigResponse(): DeleteConfigResponse {
  return { message: "" };
}

export const DeleteConfigResponse: MessageFns<DeleteConfigResponse> = {
  encode(message: DeleteConfigResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.message !== "") {
      writer.uint32(10).string(message.message);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeleteConfigResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeleteConfigResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.message = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DeleteConfigResponse {
    return { message: isSet(object.message) ? globalThis.String(object.message) : "" };
  },

  toJSON(message: DeleteConfigResponse): unknown {
    const obj: any = {};
    if (message.message !== "") {
      obj.message = message.message;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DeleteConfigResponse>, I>>(base?: I): DeleteConfigResponse {
    return DeleteConfigResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DeleteConfigResponse>, I>>(object: I): DeleteConfigResponse {
    const message = createBaseDeleteConfigResponse();
    message.message = object.message ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
