// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: proto/opengate/v1/app_settings.proto

package opengate_v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetAppSettingsRequest is the request to retrieve all app settings
type GetAppSettingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAppSettingsRequest) Reset() {
	*x = GetAppSettingsRequest{}
	mi := &file_proto_opengate_v1_app_settings_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAppSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppSettingsRequest) ProtoMessage() {}

func (x *GetAppSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_opengate_v1_app_settings_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppSettingsRequest.ProtoReflect.Descriptor instead.
func (*GetAppSettingsRequest) Descriptor() ([]byte, []int) {
	return file_proto_opengate_v1_app_settings_proto_rawDescGZIP(), []int{0}
}

// GetAppSettingsResponse contains all app settings as a key → JSON-value map
type GetAppSettingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Settings      *structpb.Struct       `protobuf:"bytes,1,opt,name=settings,proto3" json:"settings,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAppSettingsResponse) Reset() {
	*x = GetAppSettingsResponse{}
	mi := &file_proto_opengate_v1_app_settings_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAppSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppSettingsResponse) ProtoMessage() {}

func (x *GetAppSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_opengate_v1_app_settings_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppSettingsResponse.ProtoReflect.Descriptor instead.
func (*GetAppSettingsResponse) Descriptor() ([]byte, []int) {
	return file_proto_opengate_v1_app_settings_proto_rawDescGZIP(), []int{1}
}

func (x *GetAppSettingsResponse) GetSettings() *structpb.Struct {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *GetAppSettingsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// UpsertAppSettingRequest is the request to create or update a single setting
type UpsertAppSettingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         *structpb.Value        `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertAppSettingRequest) Reset() {
	*x = UpsertAppSettingRequest{}
	mi := &file_proto_opengate_v1_app_settings_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertAppSettingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertAppSettingRequest) ProtoMessage() {}

func (x *UpsertAppSettingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_opengate_v1_app_settings_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertAppSettingRequest.ProtoReflect.Descriptor instead.
func (*UpsertAppSettingRequest) Descriptor() ([]byte, []int) {
	return file_proto_opengate_v1_app_settings_proto_rawDescGZIP(), []int{2}
}

func (x *UpsertAppSettingRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *UpsertAppSettingRequest) GetValue() *structpb.Value {
	if x != nil {
		return x.Value
	}
	return nil
}

// UpsertAppSettingResponse is the response after upserting a setting
type UpsertAppSettingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertAppSettingResponse) Reset() {
	*x = UpsertAppSettingResponse{}
	mi := &file_proto_opengate_v1_app_settings_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertAppSettingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertAppSettingResponse) ProtoMessage() {}

func (x *UpsertAppSettingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_opengate_v1_app_settings_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertAppSettingResponse.ProtoReflect.Descriptor instead.
func (*UpsertAppSettingResponse) Descriptor() ([]byte, []int) {
	return file_proto_opengate_v1_app_settings_proto_rawDescGZIP(), []int{3}
}

func (x *UpsertAppSettingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_opengate_v1_app_settings_proto protoreflect.FileDescriptor

const file_proto_opengate_v1_app_settings_proto_rawDesc = "" +
	"\n" +
	"$proto/opengate/v1/app_settings.proto\x12\vopengate.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x17validate/validate.proto\"\x17\n" +
	"\x15GetAppSettingsRequest\"g\n" +
	"\x16GetAppSettingsResponse\x123\n" +
	"\bsettings\x18\x01 \x01(\v2\x17.google.protobuf.StructR\bsettings\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"b\n" +
	"\x17UpsertAppSettingRequest\x12\x19\n" +
	"\x03key\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value\"4\n" +
	"\x18UpsertAppSettingResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessageB\x0fZ\r./opengate_v1b\x06proto3"

var (
	file_proto_opengate_v1_app_settings_proto_rawDescOnce sync.Once
	file_proto_opengate_v1_app_settings_proto_rawDescData []byte
)

func file_proto_opengate_v1_app_settings_proto_rawDescGZIP() []byte {
	file_proto_opengate_v1_app_settings_proto_rawDescOnce.Do(func() {
		file_proto_opengate_v1_app_settings_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_opengate_v1_app_settings_proto_rawDesc), len(file_proto_opengate_v1_app_settings_proto_rawDesc)))
	})
	return file_proto_opengate_v1_app_settings_proto_rawDescData
}

var file_proto_opengate_v1_app_settings_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_opengate_v1_app_settings_proto_goTypes = []any{
	(*GetAppSettingsRequest)(nil),    // 0: opengate.v1.GetAppSettingsRequest
	(*GetAppSettingsResponse)(nil),   // 1: opengate.v1.GetAppSettingsResponse
	(*UpsertAppSettingRequest)(nil),  // 2: opengate.v1.UpsertAppSettingRequest
	(*UpsertAppSettingResponse)(nil), // 3: opengate.v1.UpsertAppSettingResponse
	(*structpb.Struct)(nil),          // 4: google.protobuf.Struct
	(*structpb.Value)(nil),           // 5: google.protobuf.Value
}
var file_proto_opengate_v1_app_settings_proto_depIdxs = []int32{
	4, // 0: opengate.v1.GetAppSettingsResponse.settings:type_name -> google.protobuf.Struct
	5, // 1: opengate.v1.UpsertAppSettingRequest.value:type_name -> google.protobuf.Value
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_opengate_v1_app_settings_proto_init() }
func file_proto_opengate_v1_app_settings_proto_init() {
	if File_proto_opengate_v1_app_settings_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_opengate_v1_app_settings_proto_rawDesc), len(file_proto_opengate_v1_app_settings_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_opengate_v1_app_settings_proto_goTypes,
		DependencyIndexes: file_proto_opengate_v1_app_settings_proto_depIdxs,
		MessageInfos:      file_proto_opengate_v1_app_settings_proto_msgTypes,
	}.Build()
	File_proto_opengate_v1_app_settings_proto = out.File
	file_proto_opengate_v1_app_settings_proto_goTypes = nil
	file_proto_opengate_v1_app_settings_proto_depIdxs = nil
}
