// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: proto/opengate/v1/config.proto

package opengate_v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AuthenticationException defines paths/methods excepted from authentication rules
type AuthenticationException struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Methods       []string               `protobuf:"bytes,2,rep,name=methods,proto3" json:"methods,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticationException) Reset() {
	*x = AuthenticationException{}
	mi := &file_proto_opengate_v1_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticationException) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticationException) ProtoMessage() {}

func (x *AuthenticationException) ProtoReflect() protoreflect.Message {
	mi := &file_proto_opengate_v1_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticationException.ProtoReflect.Descriptor instead.
func (*AuthenticationException) Descriptor() ([]byte, []int) {
	return file_proto_opengate_v1_config_proto_rawDescGZIP(), []int{0}
}

func (x *AuthenticationException) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *AuthenticationException) GetMethods() []string {
	if x != nil {
		return x.Methods
	}
	return nil
}

// Authentication defines authentication settings for a route
type Authentication struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Required bool                   `protobuf:"varint,1,opt,name=required,proto3" json:"required,omitempty"`
	// if required is true, excepted paths/methods do not require authentication
	// if required is false, excepted paths/methods require authentication
	Except        []*AuthenticationException `protobuf:"bytes,2,rep,name=except,proto3" json:"except,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Authentication) Reset() {
	*x = Authentication{}
	mi := &file_proto_opengate_v1_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Authentication) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Authentication) ProtoMessage() {}

func (x *Authentication) ProtoReflect() protoreflect.Message {
	mi := &file_proto_opengate_v1_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Authentication.ProtoReflect.Descriptor instead.
func (*Authentication) Descriptor() ([]byte, []int) {
	return file_proto_opengate_v1_config_proto_rawDescGZIP(), []int{1}
}

func (x *Authentication) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *Authentication) GetExcept() []*AuthenticationException {
	if x != nil {
		return x.Except
	}
	return nil
}

// Config represents a service route configuration
type Config struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PathPrefix     string                 `protobuf:"bytes,3,opt,name=path_prefix,json=pathPrefix,proto3" json:"path_prefix,omitempty"`
	TargetUrl      string                 `protobuf:"bytes,4,opt,name=target_url,json=targetUrl,proto3" json:"target_url,omitempty"`
	StripPrefix    bool                   `protobuf:"varint,5,opt,name=strip_prefix,json=stripPrefix,proto3" json:"strip_prefix,omitempty"`
	Authentication *Authentication        `protobuf:"bytes,6,opt,name=authentication,proto3" json:"authentication,omitempty"`
	Middleware     []string               `protobuf:"bytes,7,rep,name=middleware,proto3" json:"middleware,omitempty"`
	Timeout        int64                  `protobuf:"varint,8,opt,name=timeout,proto3" json:"timeout,omitempty"`                       // Timeout in nanoseconds
	CreatedAt      int64                  `protobuf:"varint,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`  // Unix timestamp
	UpdatedAt      int64                  `protobuf:"varint,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // Unix timestamp
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_proto_opengate_v1_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_proto_opengate_v1_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_proto_opengate_v1_config_proto_rawDescGZIP(), []int{2}
}

func (x *Config) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Config) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Config) GetPathPrefix() string {
	if x != nil {
		return x.PathPrefix
	}
	return ""
}

func (x *Config) GetTargetUrl() string {
	if x != nil {
		return x.TargetUrl
	}
	return ""
}

func (x *Config) GetStripPrefix() bool {
	if x != nil {
		return x.StripPrefix
	}
	return false
}

func (x *Config) GetAuthentication() *Authentication {
	if x != nil {
		return x.Authentication
	}
	return nil
}

func (x *Config) GetMiddleware() []string {
	if x != nil {
		return x.Middleware
	}
	return nil
}

func (x *Config) GetTimeout() int64 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *Config) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Config) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// CreateConfigRequest is the request to create a new config
type CreateConfigRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	PathPrefix     string                 `protobuf:"bytes,2,opt,name=path_prefix,json=pathPrefix,proto3" json:"path_prefix,omitempty"`
	TargetUrl      string                 `protobuf:"bytes,3,opt,name=target_url,json=targetUrl,proto3" json:"target_url,omitempty"`
	StripPrefix    bool                   `protobuf:"varint,4,opt,name=strip_prefix,json=stripPrefix,proto3" json:"strip_prefix,omitempty"`
	Authentication *Authentication        `protobuf:"bytes,5,opt,name=authentication,proto3" json:"authentication,omitempty"`
	Middleware     []string               `protobuf:"bytes,6,rep,name=middleware,proto3" json:"middleware,omitempty"`
	Timeout        int64                  `protobuf:"varint,7,opt,name=timeout,proto3" json:"timeout,omitempty"` // Timeout in nanoseconds, default 30s if not provided
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateConfigRequest) Reset() {
	*x = CreateConfigRequest{}
	mi := &file_proto_opengate_v1_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateConfigRequest) ProtoMessage() {}

func (x *CreateConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_opengate_v1_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateConfigRequest.ProtoReflect.Descriptor instead.
func (*CreateConfigRequest) Descriptor() ([]byte, []int) {
	return file_proto_opengate_v1_config_proto_rawDescGZIP(), []int{3}
}

func (x *CreateConfigRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateConfigRequest) GetPathPrefix() string {
	if x != nil {
		return x.PathPrefix
	}
	return ""
}

func (x *CreateConfigRequest) GetTargetUrl() string {
	if x != nil {
		return x.TargetUrl
	}
	return ""
}

func (x *CreateConfigRequest) GetStripPrefix() bool {
	if x != nil {
		return x.StripPrefix
	}
	return false
}

func (x *CreateConfigRequest) GetAuthentication() *Authentication {
	if x != nil {
		return x.Authentication
	}
	return nil
}

func (x *CreateConfigRequest) GetMiddleware() []string {
	if x != nil {
		return x.Middleware
	}
	return nil
}

func (x *CreateConfigRequest) GetTimeout() int64 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

// CreateConfigResponse is the response after creating a config
type CreateConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *Config                `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateConfigResponse) Reset() {
	*x = CreateConfigResponse{}
	mi := &file_proto_opengate_v1_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateConfigResponse) ProtoMessage() {}

func (x *CreateConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_opengate_v1_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateConfigResponse.ProtoReflect.Descriptor instead.
func (*CreateConfigResponse) Descriptor() ([]byte, []int) {
	return file_proto_opengate_v1_config_proto_rawDescGZIP(), []int{4}
}

func (x *CreateConfigResponse) GetConfig() *Config {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *CreateConfigResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// GetConfigRequest is the request to get a config by ID
type GetConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigRequest) Reset() {
	*x = GetConfigRequest{}
	mi := &file_proto_opengate_v1_config_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigRequest) ProtoMessage() {}

func (x *GetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_opengate_v1_config_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigRequest.ProtoReflect.Descriptor instead.
func (*GetConfigRequest) Descriptor() ([]byte, []int) {
	return file_proto_opengate_v1_config_proto_rawDescGZIP(), []int{5}
}

func (x *GetConfigRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// GetConfigResponse is the response containing the requested config
type GetConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *Config                `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigResponse) Reset() {
	*x = GetConfigResponse{}
	mi := &file_proto_opengate_v1_config_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigResponse) ProtoMessage() {}

func (x *GetConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_opengate_v1_config_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigResponse.ProtoReflect.Descriptor instead.
func (*GetConfigResponse) Descriptor() ([]byte, []int) {
	return file_proto_opengate_v1_config_proto_rawDescGZIP(), []int{6}
}

func (x *GetConfigResponse) GetConfig() *Config {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *GetConfigResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ListConfigsRequest is the request to list configs with pagination
type ListConfigsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Search        string                 `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"` // Optional search term for name
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConfigsRequest) Reset() {
	*x = ListConfigsRequest{}
	mi := &file_proto_opengate_v1_config_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConfigsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConfigsRequest) ProtoMessage() {}

func (x *ListConfigsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_opengate_v1_config_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConfigsRequest.ProtoReflect.Descriptor instead.
func (*ListConfigsRequest) Descriptor() ([]byte, []int) {
	return file_proto_opengate_v1_config_proto_rawDescGZIP(), []int{7}
}

func (x *ListConfigsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListConfigsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListConfigsRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

// ListConfigsResponse is the response containing a list of configs
type ListConfigsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Configs       []*Config              `protobuf:"bytes,1,rep,name=configs,proto3" json:"configs,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"` // Total count for pagination
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConfigsResponse) Reset() {
	*x = ListConfigsResponse{}
	mi := &file_proto_opengate_v1_config_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConfigsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConfigsResponse) ProtoMessage() {}

func (x *ListConfigsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_opengate_v1_config_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConfigsResponse.ProtoReflect.Descriptor instead.
func (*ListConfigsResponse) Descriptor() ([]byte, []int) {
	return file_proto_opengate_v1_config_proto_rawDescGZIP(), []int{8}
}

func (x *ListConfigsResponse) GetConfigs() []*Config {
	if x != nil {
		return x.Configs
	}
	return nil
}

func (x *ListConfigsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListConfigsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// GetRoutesRequest is the request to get all routes for routing purposes
type GetRoutesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoutesRequest) Reset() {
	*x = GetRoutesRequest{}
	mi := &file_proto_opengate_v1_config_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoutesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoutesRequest) ProtoMessage() {}

func (x *GetRoutesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_opengate_v1_config_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoutesRequest.ProtoReflect.Descriptor instead.
func (*GetRoutesRequest) Descriptor() ([]byte, []int) {
	return file_proto_opengate_v1_config_proto_rawDescGZIP(), []int{9}
}

// Route represents a simplified route for the routing manager
type Route struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	PathPrefix     string                 `protobuf:"bytes,2,opt,name=path_prefix,json=pathPrefix,proto3" json:"path_prefix,omitempty"`
	TargetUrl      string                 `protobuf:"bytes,3,opt,name=target_url,json=targetUrl,proto3" json:"target_url,omitempty"`
	StripPrefix    bool                   `protobuf:"varint,4,opt,name=strip_prefix,json=stripPrefix,proto3" json:"strip_prefix,omitempty"`
	Authentication *Authentication        `protobuf:"bytes,5,opt,name=authentication,proto3" json:"authentication,omitempty"`
	Middleware     []string               `protobuf:"bytes,6,rep,name=middleware,proto3" json:"middleware,omitempty"`
	Timeout        int64                  `protobuf:"varint,7,opt,name=timeout,proto3" json:"timeout,omitempty"`
	UpdatedAt      int64                  `protobuf:"varint,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Route) Reset() {
	*x = Route{}
	mi := &file_proto_opengate_v1_config_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Route) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Route) ProtoMessage() {}

func (x *Route) ProtoReflect() protoreflect.Message {
	mi := &file_proto_opengate_v1_config_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Route.ProtoReflect.Descriptor instead.
func (*Route) Descriptor() ([]byte, []int) {
	return file_proto_opengate_v1_config_proto_rawDescGZIP(), []int{10}
}

func (x *Route) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Route) GetPathPrefix() string {
	if x != nil {
		return x.PathPrefix
	}
	return ""
}

func (x *Route) GetTargetUrl() string {
	if x != nil {
		return x.TargetUrl
	}
	return ""
}

func (x *Route) GetStripPrefix() bool {
	if x != nil {
		return x.StripPrefix
	}
	return false
}

func (x *Route) GetAuthentication() *Authentication {
	if x != nil {
		return x.Authentication
	}
	return nil
}

func (x *Route) GetMiddleware() []string {
	if x != nil {
		return x.Middleware
	}
	return nil
}

func (x *Route) GetTimeout() int64 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *Route) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// GetRoutesResponse contains all routes for the routing manager
type GetRoutesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Routes        []*Route               `protobuf:"bytes,1,rep,name=routes,proto3" json:"routes,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoutesResponse) Reset() {
	*x = GetRoutesResponse{}
	mi := &file_proto_opengate_v1_config_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoutesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoutesResponse) ProtoMessage() {}

func (x *GetRoutesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_opengate_v1_config_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoutesResponse.ProtoReflect.Descriptor instead.
func (*GetRoutesResponse) Descriptor() ([]byte, []int) {
	return file_proto_opengate_v1_config_proto_rawDescGZIP(), []int{11}
}

func (x *GetRoutesResponse) GetRoutes() []*Route {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *GetRoutesResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// UpdateConfigRequest is the request to update an existing config
type UpdateConfigRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PathPrefix     string                 `protobuf:"bytes,3,opt,name=path_prefix,json=pathPrefix,proto3" json:"path_prefix,omitempty"`
	TargetUrl      string                 `protobuf:"bytes,4,opt,name=target_url,json=targetUrl,proto3" json:"target_url,omitempty"`
	StripPrefix    bool                   `protobuf:"varint,5,opt,name=strip_prefix,json=stripPrefix,proto3" json:"strip_prefix,omitempty"`
	Authentication *Authentication        `protobuf:"bytes,6,opt,name=authentication,proto3" json:"authentication,omitempty"`
	Middleware     []string               `protobuf:"bytes,7,rep,name=middleware,proto3" json:"middleware,omitempty"`
	Timeout        int64                  `protobuf:"varint,8,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateConfigRequest) Reset() {
	*x = UpdateConfigRequest{}
	mi := &file_proto_opengate_v1_config_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConfigRequest) ProtoMessage() {}

func (x *UpdateConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_opengate_v1_config_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConfigRequest.ProtoReflect.Descriptor instead.
func (*UpdateConfigRequest) Descriptor() ([]byte, []int) {
	return file_proto_opengate_v1_config_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateConfigRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateConfigRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateConfigRequest) GetPathPrefix() string {
	if x != nil {
		return x.PathPrefix
	}
	return ""
}

func (x *UpdateConfigRequest) GetTargetUrl() string {
	if x != nil {
		return x.TargetUrl
	}
	return ""
}

func (x *UpdateConfigRequest) GetStripPrefix() bool {
	if x != nil {
		return x.StripPrefix
	}
	return false
}

func (x *UpdateConfigRequest) GetAuthentication() *Authentication {
	if x != nil {
		return x.Authentication
	}
	return nil
}

func (x *UpdateConfigRequest) GetMiddleware() []string {
	if x != nil {
		return x.Middleware
	}
	return nil
}

func (x *UpdateConfigRequest) GetTimeout() int64 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

// UpdateConfigResponse is the response after updating a config
type UpdateConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *Config                `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateConfigResponse) Reset() {
	*x = UpdateConfigResponse{}
	mi := &file_proto_opengate_v1_config_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConfigResponse) ProtoMessage() {}

func (x *UpdateConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_opengate_v1_config_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConfigResponse.ProtoReflect.Descriptor instead.
func (*UpdateConfigResponse) Descriptor() ([]byte, []int) {
	return file_proto_opengate_v1_config_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateConfigResponse) GetConfig() *Config {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *UpdateConfigResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// DeleteConfigRequest is the request to delete a config
type DeleteConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteConfigRequest) Reset() {
	*x = DeleteConfigRequest{}
	mi := &file_proto_opengate_v1_config_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteConfigRequest) ProtoMessage() {}

func (x *DeleteConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_opengate_v1_config_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteConfigRequest.ProtoReflect.Descriptor instead.
func (*DeleteConfigRequest) Descriptor() ([]byte, []int) {
	return file_proto_opengate_v1_config_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteConfigRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// DeleteConfigResponse is the response after deleting a config
type DeleteConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteConfigResponse) Reset() {
	*x = DeleteConfigResponse{}
	mi := &file_proto_opengate_v1_config_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteConfigResponse) ProtoMessage() {}

func (x *DeleteConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_opengate_v1_config_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteConfigResponse.ProtoReflect.Descriptor instead.
func (*DeleteConfigResponse) Descriptor() ([]byte, []int) {
	return file_proto_opengate_v1_config_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteConfigResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_opengate_v1_config_proto protoreflect.FileDescriptor

const file_proto_opengate_v1_config_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/opengate/v1/config.proto\x12\vopengate.v1\x1a\x17validate/validate.proto\"G\n" +
	"\x17AuthenticationException\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\amethods\x18\x02 \x03(\tR\amethods\"j\n" +
	"\x0eAuthentication\x12\x1a\n" +
	"\brequired\x18\x01 \x01(\bR\brequired\x12<\n" +
	"\x06except\x18\x02 \x03(\v2$.opengate.v1.AuthenticationExceptionR\x06except\"\xcc\x02\n" +
	"\x06Config\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vpath_prefix\x18\x03 \x01(\tR\n" +
	"pathPrefix\x12\x1d\n" +
	"\n" +
	"target_url\x18\x04 \x01(\tR\ttargetUrl\x12!\n" +
	"\fstrip_prefix\x18\x05 \x01(\bR\vstripPrefix\x12C\n" +
	"\x0eauthentication\x18\x06 \x01(\v2\x1b.opengate.v1.AuthenticationR\x0eauthentication\x12\x1e\n" +
	"\n" +
	"middleware\x18\a \x03(\tR\n" +
	"middleware\x12\x18\n" +
	"\atimeout\x18\b \x01(\x03R\atimeout\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\x03R\tupdatedAt\"\xa6\x02\n" +
	"\x13CreateConfigRequest\x12\x1b\n" +
	"\x04name\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x04name\x12(\n" +
	"\vpath_prefix\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\n" +
	"pathPrefix\x12&\n" +
	"\n" +
	"target_url\x18\x03 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\ttargetUrl\x12!\n" +
	"\fstrip_prefix\x18\x04 \x01(\bR\vstripPrefix\x12C\n" +
	"\x0eauthentication\x18\x05 \x01(\v2\x1b.opengate.v1.AuthenticationR\x0eauthentication\x12\x1e\n" +
	"\n" +
	"middleware\x18\x06 \x03(\tR\n" +
	"middleware\x12\x18\n" +
	"\atimeout\x18\a \x01(\x03R\atimeout\"]\n" +
	"\x14CreateConfigResponse\x12+\n" +
	"\x06config\x18\x01 \x01(\v2\x13.opengate.v1.ConfigR\x06config\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"+\n" +
	"\x10GetConfigRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x02id\"Z\n" +
	"\x11GetConfigResponse\x12+\n" +
	"\x06config\x18\x01 \x01(\v2\x13.opengate.v1.ConfigR\x06config\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"n\n" +
	"\x12ListConfigsRequest\x12\x1f\n" +
	"\x05limit\x18\x01 \x01(\x05B\t\xfaB\x06\x1a\x04\x18d \x00R\x05limit\x12\x1f\n" +
	"\x06offset\x18\x02 \x01(\x05B\a\xfaB\x04\x1a\x02(\x00R\x06offset\x12\x16\n" +
	"\x06search\x18\x03 \x01(\tR\x06search\"t\n" +
	"\x13ListConfigsResponse\x12-\n" +
	"\aconfigs\x18\x01 \x03(\v2\x13.opengate.v1.ConfigR\aconfigs\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x12\n" +
	"\x10GetRoutesRequest\"\x9c\x02\n" +
	"\x05Route\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vpath_prefix\x18\x02 \x01(\tR\n" +
	"pathPrefix\x12\x1d\n" +
	"\n" +
	"target_url\x18\x03 \x01(\tR\ttargetUrl\x12!\n" +
	"\fstrip_prefix\x18\x04 \x01(\bR\vstripPrefix\x12C\n" +
	"\x0eauthentication\x18\x05 \x01(\v2\x1b.opengate.v1.AuthenticationR\x0eauthentication\x12\x1e\n" +
	"\n" +
	"middleware\x18\x06 \x03(\tR\n" +
	"middleware\x12\x18\n" +
	"\atimeout\x18\a \x01(\x03R\atimeout\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\x03R\tupdatedAt\"Y\n" +
	"\x11GetRoutesResponse\x12*\n" +
	"\x06routes\x18\x01 \x03(\v2\x12.opengate.v1.RouteR\x06routes\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xbf\x02\n" +
	"\x13UpdateConfigRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x02id\x12\x1b\n" +
	"\x04name\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x04name\x12(\n" +
	"\vpath_prefix\x18\x03 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\n" +
	"pathPrefix\x12&\n" +
	"\n" +
	"target_url\x18\x04 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\ttargetUrl\x12!\n" +
	"\fstrip_prefix\x18\x05 \x01(\bR\vstripPrefix\x12C\n" +
	"\x0eauthentication\x18\x06 \x01(\v2\x1b.opengate.v1.AuthenticationR\x0eauthentication\x12\x1e\n" +
	"\n" +
	"middleware\x18\a \x03(\tR\n" +
	"middleware\x12\x18\n" +
	"\atimeout\x18\b \x01(\x03R\atimeout\"]\n" +
	"\x14UpdateConfigResponse\x12+\n" +
	"\x06config\x18\x01 \x01(\v2\x13.opengate.v1.ConfigR\x06config\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\".\n" +
	"\x13DeleteConfigRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x02id\"0\n" +
	"\x14DeleteConfigResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessageB\x0fZ\r./opengate_v1b\x06proto3"

var (
	file_proto_opengate_v1_config_proto_rawDescOnce sync.Once
	file_proto_opengate_v1_config_proto_rawDescData []byte
)

func file_proto_opengate_v1_config_proto_rawDescGZIP() []byte {
	file_proto_opengate_v1_config_proto_rawDescOnce.Do(func() {
		file_proto_opengate_v1_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_opengate_v1_config_proto_rawDesc), len(file_proto_opengate_v1_config_proto_rawDesc)))
	})
	return file_proto_opengate_v1_config_proto_rawDescData
}

var file_proto_opengate_v1_config_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_opengate_v1_config_proto_goTypes = []any{
	(*AuthenticationException)(nil), // 0: opengate.v1.AuthenticationException
	(*Authentication)(nil),          // 1: opengate.v1.Authentication
	(*Config)(nil),                  // 2: opengate.v1.Config
	(*CreateConfigRequest)(nil),     // 3: opengate.v1.CreateConfigRequest
	(*CreateConfigResponse)(nil),    // 4: opengate.v1.CreateConfigResponse
	(*GetConfigRequest)(nil),        // 5: opengate.v1.GetConfigRequest
	(*GetConfigResponse)(nil),       // 6: opengate.v1.GetConfigResponse
	(*ListConfigsRequest)(nil),      // 7: opengate.v1.ListConfigsRequest
	(*ListConfigsResponse)(nil),     // 8: opengate.v1.ListConfigsResponse
	(*GetRoutesRequest)(nil),        // 9: opengate.v1.GetRoutesRequest
	(*Route)(nil),                   // 10: opengate.v1.Route
	(*GetRoutesResponse)(nil),       // 11: opengate.v1.GetRoutesResponse
	(*UpdateConfigRequest)(nil),     // 12: opengate.v1.UpdateConfigRequest
	(*UpdateConfigResponse)(nil),    // 13: opengate.v1.UpdateConfigResponse
	(*DeleteConfigRequest)(nil),     // 14: opengate.v1.DeleteConfigRequest
	(*DeleteConfigResponse)(nil),    // 15: opengate.v1.DeleteConfigResponse
}
var file_proto_opengate_v1_config_proto_depIdxs = []int32{
	0,  // 0: opengate.v1.Authentication.except:type_name -> opengate.v1.AuthenticationException
	1,  // 1: opengate.v1.Config.authentication:type_name -> opengate.v1.Authentication
	1,  // 2: opengate.v1.CreateConfigRequest.authentication:type_name -> opengate.v1.Authentication
	2,  // 3: opengate.v1.CreateConfigResponse.config:type_name -> opengate.v1.Config
	2,  // 4: opengate.v1.GetConfigResponse.config:type_name -> opengate.v1.Config
	2,  // 5: opengate.v1.ListConfigsResponse.configs:type_name -> opengate.v1.Config
	1,  // 6: opengate.v1.Route.authentication:type_name -> opengate.v1.Authentication
	10, // 7: opengate.v1.GetRoutesResponse.routes:type_name -> opengate.v1.Route
	1,  // 8: opengate.v1.UpdateConfigRequest.authentication:type_name -> opengate.v1.Authentication
	2,  // 9: opengate.v1.UpdateConfigResponse.config:type_name -> opengate.v1.Config
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_opengate_v1_config_proto_init() }
func file_proto_opengate_v1_config_proto_init() {
	if File_proto_opengate_v1_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_opengate_v1_config_proto_rawDesc), len(file_proto_opengate_v1_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_opengate_v1_config_proto_goTypes,
		DependencyIndexes: file_proto_opengate_v1_config_proto_depIdxs,
		MessageInfos:      file_proto_opengate_v1_config_proto_msgTypes,
	}.Build()
	File_proto_opengate_v1_config_proto = out.File
	file_proto_opengate_v1_config_proto_goTypes = nil
	file_proto_opengate_v1_config_proto_depIdxs = nil
}
